name: JohnnyAdamsSanga
favicon: null
layout_spectrum: 1
typography_spectrum: 0.09281
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161116'
    - '#faebdb'
    - '#cbc3b9'
    - '#a9907f'
    - '#1c4c7b'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
